# Generated by Django 4.0.3 on 2022-06-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('academic_title', models.CharField(blank=True, max_length=200, verbose_name='Ученое звание')),
                ('academic_status', models.CharField(blank=True, max_length=200, verbose_name='Ученая степень')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема научного доклада')),
                ('face_type', models.CharField(choices=[('face_1', 'Юридическое лицо'), ('face_2', 'Физическое лицо')], default=1, max_length=20, verbose_name='Лицо')),
                ('format', models.CharField(choices=[('face_ofline', 'Очно'), ('face_online', 'Дистанционно')], default=1, max_length=20, verbose_name='Формат участия')),
                ('role', models.CharField(choices=[('role_1', 'Слушатель'), ('role_2', 'Докладчик')], default=1, max_length=20, verbose_name='Роль')),
                ('company', models.CharField(max_length=50, verbose_name='Организация')),
                ('company_status', models.CharField(max_length=50, verbose_name='Должность')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Телефон')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
                ('paper', models.CharField(choices=[('paper_1', 'Без статьи и без доклада'), ('paper_2', 'Только публикация'), ('paper_3', 'Только устный доклад '), ('paper_4', 'Устный доклад + публикация статьи')], default=1, max_length=20, verbose_name='Доклад / статья')),
                ('hotel1', models.BooleanField(default=False, max_length=50, verbose_name='Самостоятельный выбор жилья в г. Бишкек')),
                ('hotel2', models.BooleanField(default=False, max_length=50, verbose_name='Отель “Jannat Regency”, г. Бишкек')),
                ('hotel3', models.BooleanField(default=False, max_length=50, verbose_name='Отель “Золотой Дракон”, г. Бишкек')),
                ('hotel4', models.BooleanField(default=False, max_length=50, verbose_name='Отель “Talisman Village”, Иссык-Куль')),
                ('files', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ComitetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название комитета',
                'verbose_name_plural': 'Названия комитета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='На русском языке', max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='KeySpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Ключевой спикер',
                'verbose_name_plural': 'Ключевые спикеры',
            },
        ),
        migrations.CreateModel(
            name='ParticipantCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='Дата')),
                ('round', models.CharField(max_length=1, verbose_name='Этап')),
                ('position', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='Сomitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.TextField(blank=True, verbose_name='Должности')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='en.comitettype', verbose_name='Комитет')),
            ],
            options={
                'verbose_name': 'Член комитет',
                'verbose_name_plural': 'Члены Комитет',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ф.И.О.')),
                ('company', models.CharField(default='', max_length=250, verbose_name='Организация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to='en.participantcategories', verbose_name='Категория участника')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='participant', to='en.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
