# Generated by Django 4.0.3 on 2022-07-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0002_alter_comitettype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comitettype',
            options={'verbose_name': 'Комитет', 'verbose_name_plural': 'Комитеты'},
        ),
        migrations.AlterField(
            model_name='сomitet',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='en.country', verbose_name='Комитет'),
        ),
        migrations.AlterField(
            model_name='сomitet',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='en.comitettype', verbose_name='Комитет'),
        ),
    ]
