# Generated by Django 4.0.3 on 2022-07-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0003_alter_comitettype_options_alter_сomitet_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='en.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='сomitet',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='en.country', verbose_name='Страна'),
        ),
    ]
