# Generated by Django 4.0.3 on 2022-07-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0003_alter_client_country_alter_participant_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
