# Generated by Django 4.0.3 on 2022-07-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0006_remove_program_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomitet',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ru.comitettype', verbose_name='Комитет'),
        ),
    ]
